### ISSUE TITLE
web link broken in Postman how to guide

### ISSUE THREAD

**Issue by collinweeks** [DigitalGlobe/Postman#1]
https://gbdxdocs.digitalglobe.com/v1/docs/lesson-how-to-find-your-api-key-1 
returns 404

**Comment by collinweeks** [comment]
this link works. Maybe update the GitHub Postman

https://gbdxdocs.digitalglobe.com/v1/docs/lessonfind-your-api-key

**Comment by christyberman** [comment]
API key has been removed from authentication and references to API key have been removed from documentation.
